### ISSUE TITLE
Error in latest.log if mod is active

### ISSUE THREAD

**Issue by Cape-City** [constellation-mc/blame-log#3]
Hi,

i don't know if this error is crashing the game sometimes, but i think any error which isn't there is better :D

[12:56:06] [main/INFO]: (Dark Matter / InstrumentationAccess#bootstrap) Attaching instrumentation agent to VM.
[12:56:06] [main/ERROR]: (Dark Matter / InstrumentationAccess#bootstrap) An error occurred during an attempt to attach an instrumentation agent, which might be due to spaces in the path of the game's installation.
java.lang.NullPointerException: Couldn't find included "jar/dark_matter_instrumentation_agent.jar"!
	at me.melontini.dark_matter.danger.instrumentation.InstrumentationAccess.bootstrap(InstrumentationAccess.java:184) ~[dark-matter-danger-0.6.0-1.18.2-144ffa74e35952d.jar:?]
	at me.melontini.dark_matter.danger.instrumentation.InstrumentationAccess.<clinit>(InstrumentationAccess.java:154) ~[dark-matter-danger-0.6.0-1.18.2-144ffa74e35952d.jar:?]
	at me.melontini.blamelog.BlamePlugin.<clinit>(BlamePlugin.java:40) ~[blame-log-0.3.0-1.18.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96) ~[fabric-loader-0.14.21.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
[12:56:06] [main/ERROR]: [BlameLog] Instrumentation went to get some milk, but never came back...

[latest.log](https://github.com/melontini/blame-log/files/12038577/latest.log)

It's funny the error says something about "Dark Matter", but this mod wasn't active at this time and when it's active, the error is the same.

**Comment by zenfyrdev** [comment]
Hmm, this was supposed to be fixed 😶‍🌫️

You're also saying that it only happens sometimes?

**Comment by Cape-City** [comment]
The error is shown always in latest.log when the mod BlameLog is active. I was just confused 'coz the error said something with "Dark Matter" and i thought it was the fault of this mod and disabled it to try it out, but the error stays. Then i found out, only if the mod BlameLog is active, this error is shown up in latest.log.

**Comment by zenfyrdev** [comment]
Should be fixed in 0.3.1
