### ISSUE TITLE
[BUG] MC isn't loading while version blame-log-0.3.2-1.18.jar is active

### ISSUE THREAD

**Issue by Cape-City** [constellation-mc/blame-log#4]
Hi,

with the version 0.3.1 everything works as it should, but after update to version 0.3.2 the game is stuck while loading.

Here is the latest.log with version 0.3.2:
[latest.log](https://github.com/melontini/blame-log/files/12436587/latest.log)

Here is the latest.log with version 0.3.1:
[latest.log](https://github.com/melontini/blame-log/files/12436639/latest.log)

MC 1.19.3
Fabric 0.14.22
fabric-api-0.76.1+1.19.3.jar

**Comment by zenfyrdev** [comment]
Hi, thanks for the report. Unfortunately, I can't confirm this. The game launches fine on all MC versions I tested it on.

**Comment by Cape-City** [comment]
Maybe it has to do with an incomp with one of the 445 other mods i have installed, but this incomp isn't there, if i use the v0.3.1.
The question is what changes has been taken place between these 2 versions?

**Comment by zenfyrdev** [comment]
There was a major-ish Dark Matter update, but there were hardly any changes related to BlameLog/Danger. Even Base was barely affected.

The only one I can think of is the ClassLoader switch `FabricLoader.class.getClassLoader()` -> `ClassLoader.getSystemClassLoader()` in Danger. But if something went wrong here, the game would've crashed immediately.

**Comment by Cape-City** [comment]
The Dark Matter mod is also in its last version installed (dark-matter-1.1.0-1.19.3.jar). The pain is, that MC doesn't produced any error in the log, just freeze exactly at the same point every time.

**Comment by zenfyrdev** [comment]
Can you check this version? https://github.com/melontini/blame-log/suites/16613259664/artifacts/949118009

**Comment by Cape-City** [comment]
Hi,

it freezes again at the same time during startup, sorry :(

[latest.log](https://github.com/melontini/blame-log/files/12763774/latest.log)

**Comment by zenfyrdev** [comment]
I honestly have no idea. If you're playing a modpack, could you send me the link?

**Comment by Cape-City** [comment]
It's my modpack:

https://www.curseforge.com/minecraft/modpacks/monty-mcdonnells-a-new-world

**Comment by zenfyrdev** [comment]
Can you try reproducing with MemoryLeakFix v1.1.2? There seems to be a conflict with v1.0.0 and MixinExtras 0.2.0-rc.4

**Comment by Cape-City** [comment]
Hi,

even with blame-log-0.3.2-1.18.jar or blame-log-0.4.0-1.18.jar and MemoryLeakFix 1.1.2 or MemoryLeakFix completly disabled, this error happens with that freeze.

[latest.log](https://github.com/melontini/blame-log/files/12775173/latest.log)

**Comment by zenfyrdev** [comment]
Hmm. Could you please dump the debug.log using https://modrinth.com/mod/better-log4j-config with this config https://github.com/FabricMC/fabric-loom/blob/dev/1.4/src/main/resources/log4j2.fabric.xml ? Also, which java vendor are you using? (e.g. Adoptium, Azul Zulu, GraalVM, IBM, OpenJ9 etc.)

**Comment by Cape-City** [comment]
Hi,

CurseForge is using the OpenJDK Binary:

![grafik](https://github.com/melontini/blame-log/assets/122229367/9d87188a-d0c4-47b8-ae80-094dba6e875c)

Here is the latest.log file with the better_log4j_config mod active (the debug.log is complete empty):

[latest.log](https://github.com/melontini/blame-log/files/12776912/latest.log)

![grafik](https://github.com/melontini/blame-log/assets/122229367/a7ee08d4-a26a-4895-895d-a8c6cf399c1f)

**Comment by Cape-City** [comment]
If using the "working" blame-log mod again, this is plottet in the latest.log:
(did mc just not load the mod in version 0.3.1 and that's why the game is not crashing?):

12:19:59.521
FabricLoader/Mixin
main
Error loading companion plugin class [me.melontini.blamelog.BlamePlugin] for mixin config [blame-log.mixins.json]. The plugin may be out of date: NoClassDefFoundError:me/melontini/dark_matter/util/Utilities
java.lang.NoClassDefFoundError: me/melontini/dark_matter/util/Utilities
	at me.melontini.blamelog.BlamePlugin.<clinit>(BlamePlugin.java:29)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: me.melontini.dark_matter.util.Utilities
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 27 more
12:19:59.545
FabricLoader/Mixin
main
Reference map 'blame-log-refmap.json' for blame-log.mixins.json could not be read. If this is a development environment you can ignore this message

Here is the latest.log when MC starts normally into the game:

[latest.log](https://github.com/melontini/blame-log/files/12776947/latest.log)

**Comment by zenfyrdev** [comment]
Ah, sorry, the error happens before BetterLog4J is inited. Can you try this version https://github.com/melontini/better_log4j_config/suites/16755696946/artifacts/956993108 with the hanging version of BlameLog?

**Comment by Cape-City** [comment]
Here are the two logs:

[debug.log](https://github.com/melontini/blame-log/files/12777245/debug.log)
[latest.log](https://github.com/melontini/blame-log/files/12777246/latest.log)
